/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IotdslUiModule extends AbstractIotdslUiModule {

	public IotdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
