/*
 * generated by Xtext 2.20.0
 */
package dk.klevang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IotdslStandaloneSetup extends IotdslStandaloneSetupGenerated {

	public static void doSetup() {
		new IotdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
