/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.validation;

import org.eclipse.xtext.validation.Check;

import dk.klevang.iotdsl.Board;
import dk.klevang.iotdsl.IotdslPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class IotdslValidator extends AbstractIotdslValidator {
	
private static final String INVALID_BOARD_TYPE = "Unsupported Board Type";

//	public static final INVALID_NAME = 'invalidName'
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					IotdslPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	@Check
	public void checkBoard (Board bt) {
		if(!bt.getBoardType().equals("Pycom") && !bt.getBoardType().equals("Esp32")) {
			error("Unsupported Board Type", IotdslPackage.Literals.BOARD__BOARD_TYPE, INVALID_BOARD_TYPE);
		}
		
	}

}
