/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.scoping;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import dk.klevang.iotdsl.DotReference;
import dk.klevang.iotdsl.Ref;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class IotdslScopeProvider extends AbstractIotdslScopeProvider {
	
	@Override
	public IScope getScope(EObject context, EReference reference) {
   	    if (context instanceof DotReference) 
   	    {
	        EObject rootElement = EcoreUtil2.getRootContainer(context);
	        List<Ref> candidates = EcoreUtil2.getAllContentsOfType(rootElement, Ref.class);
	       
	        return Scopes.scopeFor(candidates);
	    }
	    return super.getScope(context, reference);
	}

}
