/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.klevang.IotdslRuntimeModule;
import dk.klevang.IotdslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IotdslIdeSetup extends IotdslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IotdslRuntimeModule(), new IotdslIdeModule()));
	}
	
}
